spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:library}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    show-sql: true

application:
  security:
    signature: ${SIGNATURE:test-spd-ukraine-library-signature}
    lifetime: 1d
